# Generated by Django 2.2.7 on 2019-11-30 18:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('Descripcion', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('nombreCriatura', models.CharField(max_length=200)),
            ],
            options={
                'permissions': (('administrador', 'Es administrador'), ('cliente', 'Es cliente')),
            },
        ),
    ]
