# Generated by Django 2.2.7 on 2019-11-30 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enciclopedia', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='url',
            new_name='criarue',
        ),
        migrations.RemoveField(
            model_name='post',
            name='name',
        ),
    ]
