# Generated by Django 2.2.6 on 2019-11-10 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enciclopedia', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': (('administrador', 'Es administrador'), ('cliente', 'Es cliente'))},
        ),
    ]
