# Generated by Django 2.2.6 on 2019-11-15 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enciclopedia', '0002_auto_20191110_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='url',
            field=models.CharField(default=-1.0, max_length=200),
            preserve_default=False,
        ),
    ]
