# Generated by Django 2.2.7 on 2019-12-01 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enciclopedia', '0002_auto_20191130_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameCreature', models.CharField(max_length=40)),
            ],
        ),
    ]
