# Generated by Django 2.2.7 on 2019-12-01 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enciclopedia', '0003_creature'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='criature',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='enciclopedia.Creature'),
            preserve_default=False,
        ),
    ]
