# Generated by Django 2.2.7 on 2019-12-01 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enciclopedia', '0004_post_criature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='criature',
        ),
        migrations.AlterField(
            model_name='post',
            name='criarue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enciclopedia.Creature'),
        ),
    ]
