# Generated by Django 2.2.6 on 2019-11-29 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('enciclopedia', '0006_auto_20191114_2307'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombresUsuario', models.CharField(max_length=120, verbose_name='Usuario Name')),
                ('apellidoUsuario', models.CharField(max_length=120, verbose_name='Usuario Name')),
                ('contraseña', models.CharField(max_length=300)),
                ('email_address', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('admin', 'Es admin'), ('duoc.2019', 'Es duoc.2019')),
            },
        ),
        migrations.CreateModel(
            name='ImagenGalleria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/img/')),
                ('nombreimagen', models.CharField(max_length=120)),
                ('criatura', models.CharField(max_length=120)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='img', to='enciclopedia.Usuario')),
            ],
        ),
    ]
