# Generated by Django 2.2.6 on 2019-11-29 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enciclopedia', '0007_imagengalleria_usuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
    ]
