# Generated by Django 2.2.6 on 2019-11-29 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enciclopedia', '0008_auto_20191129_1436'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': (('administrador', 'Es administrador'), ('cliente', 'Es cliente'))},
        ),
    ]
