# Generated by Django 2.2.6 on 2019-11-29 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enciclopedia', '0009_auto_20191129_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='url2',
            field=models.CharField(default=-1.0, max_length=200),
            preserve_default=False,
        ),
    ]
