# Generated by Django 2.2.6 on 2019-11-29 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enciclopedia', '0010_post_url2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='url2',
        ),
    ]
